services:
  databaseus:
    image: databasus/databasus:latest
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./databasus-data:/databasus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:4005/api/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 127.0.0.1:4005:4005
    restart: unless-stopped
