services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./etc_wireguard:/etc/wireguard
    ports:
      - 55523:55523/udp
      - 127.0.0.1:8280:80
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      TZ: Europe/Berlin
      HOST: 0.0.0.0 # ui ip binding
      PORT: 80 # ui port
      INSECURE: true # Allow ui http
      #INIT_ENABLED: true
      #INIT_USERNAME: Username
      #INIT_PASSWORD: xxx
      #INIT_HOST: domain.tld
      #INIT_PORT: 55523
      #INIT_IPV4_CIDR: 10.8.0.0/24
      #INIT_IPV6_CIDR: fd3a:841e:8402:4f00::/64
    restart: unless-stopped
